# Environment (qa, staging, dev)
environment=qa

# Web Config
browser=chrome
username=vinhtran
password=Test12345
web.url=https://ctflearn.com/user/login
qa.web.url=https://ctflearn.com
staging.web.url=https://ctflearn.com
dev.web.url=https://ctflearn.com

# API Config
qa.api.url=https://reqres.in/api
staging.api.url=https://reqres.in/api
dev.api.url=https://reqres.in/api
api.key=pub_71fc80d68206e02217a8ac087a08aaadd202dced415469bc4da30390ed484d57

# Mobile Config
platform=android
appium.server=http://127.0.0.1:4723
android.app.path=/path/to/app.apk
ios.app.path=/path/to/app.ipa
android.device.name=emulator-5554
ios.device.name=iPhone Simulator